Support import git repository
microsoft/terraform-provider-azuredevops pull request #118
Opened 2020-07-31 06:33 UTC by xuzhang3

## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Issue Number: #43  #45 

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information

2020-07-31 12:04 UTC, EliiseS requested changes
Looks great! I got just a few change requests `:D

2020-07-31 12:04 UTC, EliiseS commented on website/docs/r/azure_git_repository.html.markdown
>  - `init_type` - (Required) The type of repository to create. Valid values: `Uninitialized` or `Clean`. Defaults to `Uninitialized`.
Missing import mention

```suggestion
- `init_type` - (Required) The type of repository to create. Valid values: `Uninitialized`, `Clean` or `Import`. Defaults to `Uninitialized`.
```

2020-07-31 12:04 UTC, EliiseS commented on azuredevops/internal/service/git/resource_git_repository.go
> +		if strings.EqualFold(initialization.sourceType, "Git") {
These two if statements can be merged

2020-07-31 12:04 UTC, EliiseS commented on azuredevops/internal/service/git/resource_git_repository.go
> +							Default:      "Git",
Add required
```suggestion
							Default:      "Git",
							RequiredWith: []string{"initialization .0.source_url"},
```

2020-07-31 12:04 UTC, EliiseS commented on azuredevops/internal/service/git/resource_git_repository.go
> +							ValidateFunc: validation.IsURLWithHTTPorHTTPS,
Add required
```suggestion
							ValidateFunc: validation.IsURLWithHTTPorHTTPS,
							RequiredWith: []string{"initialization .0.source_typel"},
```

2020-08-03 05:30 UTC, xuzhang3 commented on azuredevops/internal/service/git/resource_git_repository.go
> +		if strings.EqualFold(initialization.sourceType, "Git") {
Agree with you. The reason why have two if statement is web UI support two types import: `git`, `tfvc`, I only implement the `git` import feature. :D

2020-08-12 05:12 UTC, merged

2020-08-12 14:09 UTC, sdebruyn commented on azuredevops/internal/service/git/resource_git_repository.go
> +		if strings.EqualFold(initialization.sourceType, "Git") {
You forgot to check if `initialization` is nil here @xuzhang3