Feature/service principal entitlement
microsoft/terraform-provider-azuredevops pull request #1253
Opened 2024-12-17 15:01 UTC by jgschwendswica

## All Submissions:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] I have updated the documentation accordingly.
* [X] I have added tests to cover my changes.
* [X] All new and existing tests passed.
* [X] My code follows the code style of this project.
* [X] I ran lint checks locally prior to submission.
* [X] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?
This PR adds the resource azuredevops_service_principal_entitlement and the data data_service_principal which have been missing so far.
This will help improve the overall automation capabilities around ADO.

Issue Number:
https://github.com/microsoft/terraform-provider-azuredevops/issues/1071

There's also a rather old PR addressing the same issue, however it lacks of the data part:
https://github.com/microsoft/terraform-provider-azuredevops/pull/1028

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [X] No

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information

![image](https://github.com/user-attachments/assets/faf7e04c-d276-4f22-982f-57ac30d1e926)
![image](https://github.com/user-attachments/assets/604fc278-31d5-4f75-a40e-e2b229f9d74f)

2024-12-17 15:20 UTC, jgschwendswica commented
@microsoft-github-policy-service agree company="SWICA GESUNDHEITSORGANISATION"

2024-12-18 08:58 UTC, xuzhang3 commented
Duplicate of #1028

2025-01-09 07:30 UTC, xuzhang3 requested changes
@jgschwendswica left some comments others looks good to me. I will take another look once these fixed.

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/data_service_principal_test.go
> +}
```suggestion
func hclServicePrincipalDataBasic(servicePrincipalObjectId string) string {
	return fmt.Sprintf(`
%s

data "azuredevops_service_principal" "test" {
  display_name = azuredevops_service_principal_entitlement.test.display_name
}`, testutils.HclServicePrincipleEntitlementResource(servicePrincipalObjectId))
}
```

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +	return response, nil
No need to check the `descriptor` as this is the only parameter needed
```suggestion
	return clients.GraphClient.GetServicePrincipal(clients.Ctx, graph.GetServicePrincipalArgs{
		ServicePrincipalDescriptor: servicePrincipalDescriptor,
	})
```

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +	return response, nil
```suggestion
	return clients.IdentityClient.ReadIdentities(clients.Ctx, identity.ReadIdentitiesArgs{
		SearchFilter: searchFilter, // Filter to get users
		FilterValue:  &filterValue,
	})
```

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +	for _, servicePrincipal := range *servicePrincipals {
```suggestion
        if servicePrincipals == nil || len(*servicePrincipals) == 0 {
		return nil
	}
	for _, servicePrincipal := range *servicePrincipals {
```

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +	if servicePrincipals == nil {
```suggestion
	if servicePrincipals == nil || len(*servicePrincipals) == 0 {
```

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +	filteredServicePrincipals, err := getIdentityServicePrincipalsWithFilterValue(clients, searchFilter, displayName)
We can fast fail here if `filteredServicePrincipals` is nil or empty

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +		results[i] = newUser
```suggestion
		results = append(results, identity.Identity{
			Id:                  servicePrincipal.Id,
			Descriptor:          servicePrincipal.Descriptor,
			ProviderDisplayName: servicePrincipal.ProviderDisplayName,
			SubjectDescriptor:   servicePrincipal.SubjectDescriptor,
		})
```

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +		return fmt.Errorf("%s. Error: %v", errMsg, err)
```suggestion
		if servicePrincipalDescriptor != nil {
			return fmt.Errorf(" Finding service principal with Descriptor %s", *servicePrincipalDescriptor)
		}
		return fmt.Errorf(" Finding service principal. Error: %v", err)
```

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +		storageKey, err := clients.GraphClient.GetStorageKey(clients.Ctx, graph.GetStorageKeyArgs{
Unused code should be removed

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +		if strings.Contains(strings.ToLower(*servicePrincipal.ProviderDisplayName), strings.ToLower(displayName)) {
Why contains instead of exact equality? Will this find the wrong SPN?

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +			Read: schema.DefaultTimeout(30 * time.Minute),
Do we need a 30 mins for timeout or 3/5 mins is enough?

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +			Create: schema.DefaultTimeout(30 * time.Minute),
Timeout of 5 mins should be enough  to create/update and 2 mins for read

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +			"origin": {
Since `origin_id` is required, `origin` should be `Required: true` too and `RequiredWith` can be removed

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +	d.Set("descriptor", *servicePrincipalEntitlement.ServicePrincipal.Descriptor)
```suggestion
	if servicePrincipalEntitlement != nil {
		if servicePrincipalEntitlement.ServicePrincipal != nil {
			d.Set("origin", *servicePrincipalEntitlement.ServicePrincipal.Origin)
			if servicePrincipalEntitlement.ServicePrincipal.OriginId != nil {
				d.Set("origin_id", *servicePrincipalEntitlement.ServicePrincipal.OriginId)
			}
			d.Set("display_name", *servicePrincipalEntitlement.ServicePrincipal.DisplayName)
			d.Set("descriptor", *servicePrincipalEntitlement.ServicePrincipal.Descriptor)
		}

		if servicePrincipalEntitlement.AccessLevel != nil {
			d.Set("account_license_type", string(*servicePrincipalEntitlement.AccessLevel.AccountLicenseType))
			d.Set("licensing_source", *servicePrincipalEntitlement.AccessLevel.LicensingSource)
		}
	}
```

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +	}, nil
Since the `AccountLicenseType` and `LicensingSource`  has been constrained in the scheme definition, we can directly  use it without checking the values
```suggestion
	return &memberentitlementmanagement.ServicePrincipalEntitlement{
		AccessLevel: &licensing.AccessLevel{
			AccountLicenseType: converter.ToPtr(licensing.AccountLicenseType(d.Get("account_license_type").(string))),
			LicensingSource:    converter.ToPtr(licensing.LicensingSource(d.Get("licensing_source").(string))),
		},
		ServicePrincipal: &graph.GraphServicePrincipal{
			Origin:      converter.ToPtr(d.Get("origin").(string)),
			OriginId:    converter.ToPtr(d.Get("origin_id").(string)),
			DisplayName: converter.ToPtr(d.Get("display_name").(string)),
			Descriptor:  converter.ToPtr(d.Get("descriptor").(string)),
			SubjectKind: converter.String("servicePrincipal"),
		},
	}, nil
```

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +	}
`account_license_type` and `licensing_source` have constraints and default values in the definition ​​and can be used without checking

2025-01-09 07:30 UTC, xuzhang3 commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +	if !*patchResponse.IsSuccess {
```suggestion
    if patchResponse != nil && patchResponse.IsSuccess != nil && !*patchResponse.IsSuccess {
```

2025-01-09 07:30 UTC, xuzhang3 commented on website/docs/r/service_principal_entitlement.html.markdown
> +  origin_id = "TODO"
```suggestion
  origin_id = "00000000-0000-0000-0000-000000000000"
```

2025-01-09 07:30 UTC, xuzhang3 commented on website/docs/r/service_principal_entitlement.html.markdown
> +* `account_license_type` - (Optional) TODO.
We can add actual description instead of TODO

2025-01-09 07:30 UTC, xuzhang3 commented on website/docs/d/service_principal.html.markdown
> +* `descriptor` - TODO.
We can add actual description instead of TODO

2025-01-09 10:15 UTC, jgschwendswica commented on azuredevops/internal/service/graph/data_service_principal.go
> +	filteredServicePrincipals, err := getIdentityServicePrincipalsWithFilterValue(clients, searchFilter, displayName)
I'm now checking for nil and empty as well.

2025-01-09 10:19 UTC, jgschwendswica commented on azuredevops/internal/service/graph/data_service_principal.go
> +		if strings.Contains(strings.ToLower(*servicePrincipal.ProviderDisplayName), strings.ToLower(displayName)) {
I oriented myself towards the implementation of data_identity_user.
I'm not entirely sure what the reason for this implementation is, but it would at least be consistent.

Should I rather change it?

2025-01-09 10:19 UTC, jgschwendswica commented on azuredevops/internal/service/graph/data_service_principal.go
> +			Read: schema.DefaultTimeout(30 * time.Minute),
5 mins should be fine

2025-01-09 10:24 UTC, jgschwendswica commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +			"origin": {
If I set 'origin' required as well, you need to provide it every time which is not very convenient.
Since currently only AAD is supported as origin anyway, I thought about getting rid off entirely.

What's your thoughts on this?

2025-01-09 10:27 UTC, jgschwendswica commented
@xuzhang3 thank you very much for the detailled review.
I've incorporated most of your suggested changes.
There are two leftover's where some additional inputs would be helpful

2025-01-14 03:19 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +		if strings.Contains(strings.ToLower(*servicePrincipal.ProviderDisplayName), strings.ToLower(displayName)) {
I thought the service would return all identities with the same prefix, e.g. if `filterName=name` then `name1` and `name2` would be returned. I checked the API and found that it is not the case, the service handle this.

2025-01-14 05:56 UTC, xuzhang3 commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +			"origin": {
I agree with you. Also I tried that even with AAD resources, you can ignore the `origin`

2025-01-14 06:04 UTC, xuzhang3 requested changes

2025-01-14 06:04 UTC, xuzhang3 commented on website/docs/d/service_principal.html.markdown
> +* `display_name` - (Required) TODO. Changing this forces a new Service Principal to be created.
```suggestion
* `display_name` - (Required) The Display Name of the Service Principal. Changing this forces a new Service Principal to be created.
```

2025-01-14 06:04 UTC, xuzhang3 commented on website/docs/d/service_principal.html.markdown
> +* `descriptor` - TODO.
```suggestion
* `descriptor` - The descriptor of the Service Principal.
```

2025-01-14 06:04 UTC, xuzhang3 commented on website/docs/d/service_principal.html.markdown
> +* `origin` - TODO.
```suggestion
* `origin` - The origin of the Service Principal.
```

2025-01-14 06:04 UTC, xuzhang3 commented on website/docs/d/service_principal.html.markdown
> +* `origin_id` - The ID of the TODO.
```suggestion
* `origin_id` - The origin ID of the Service Principal..
```

2025-01-14 06:04 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +	results := make([]identity.Identity, len(*servicePrincipals))
```suggestion
	results := make([]identity.Identity, 0)
```

2025-01-14 13:47 UTC, jgschwendswica commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +			"origin": {
So should I completly remove `origin`?

2025-01-14 13:48 UTC, jgschwendswica commented on azuredevops/internal/service/graph/data_service_principal.go
> +		if strings.Contains(strings.ToLower(*servicePrincipal.ProviderDisplayName), strings.ToLower(displayName)) {
So no changes needed?

2025-01-15 02:20 UTC, xuzhang3 commented
```log
=== RUN   TestAccServicePrincipalDataSource_Read_HappyPath
=== PAUSE TestAccServicePrincipalDataSource_Read_HappyPath
=== CONT  TestAccServicePrincipalDataSource_Read_HappyPath
--- PASS: TestAccServicePrincipalDataSource_Read_HappyPath (25.53s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        41.932s

=== RUN   TestAccServicePrincipalEntitlement_Create
=== PAUSE TestAccServicePrincipalEntitlement_Create
=== CONT  TestAccServicePrincipalEntitlement_Create
--- PASS: TestAccServicePrincipalEntitlement_Create (12.39s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        13.308s

```

2025-01-15 02:20 UTC, xuzhang3 approved these changes

2025-01-15 02:20 UTC, merged

2025-01-15 03:32 UTC, xuzhang3 commented on azuredevops/internal/service/memberentitlementmanagement/resource_service_principal_entitlement.go
> +			"origin": {
we can keep it

2025-01-15 03:32 UTC, xuzhang3 commented on azuredevops/internal/service/graph/data_service_principal.go
> +		if strings.Contains(strings.ToLower(*servicePrincipal.ProviderDisplayName), strings.ToLower(displayName)) {
yes, need changes needed

2025-01-15 09:31 UTC, jgschwendswica commented
@xuzhang3 Thank you for the detailled PR Review!
It was a very helpful since i'm Terraform heavy user, but don't have a lot of GO experience so far.
It was fun!

2025-08-27 13:48 UTC, keisari-ch commented
Hi,

What permissions are required to configure this resource ?

I can manage it if i use a PAT token, but i cant figure out how to configure it with a service principal which authenticates via azure token. As i cant create a PAT token for the service principal running the terraform code...