Add Npm registry service connection
microsoft/terraform-provider-azuredevops pull request #335
Opened 2021-03-21 21:25 UTC by pasqualedevita

## All Submissions:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.
* [ ] My code follows the code style of this project.
* [ ] I ran lint checks locally prior to submission.
* [ ] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Issue Number:

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [ ] No

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information

2021-03-21 22:56 UTC, pasqualedevita commented
Test FAILs seems not related to this PR

2021-03-24 02:51 UTC, xuzhang3 commented
> Test FAILs seems not related to this PR

Integration test, can be ignored.

2021-03-24 05:53 UTC, xuzhang3 commented on website/docs/r/serviceendpoint_npm.markdown
> +  access_token          = "0000000000000000000000000000000000000000"
```suggestion
  access_token          = "00000000-0000-0000-0000-000000000000"
```

2021-03-24 07:14 UTC, xuzhang3 requested changes
Hi @pasqualedevita Thanks for you PR.  Few changes requested.
`serviceendpoint_npm.markdown` should rename to `serviceendpoint_npm.html.markdown` otherwise the document navigation menu can not locate the document.

2021-03-24 07:14 UTC, xuzhang3 commented on azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_npm.go
> +		Description:      "Authentication token generated through npm (go to Npm > Account > Access Tokens -> Generate New Token)",
1. Not all of  the NPM registries have the same navigation style,  suggest remove `(go to Npm > Account > Access Tokens -> Generate New Token)` 
2. Suggest change the description to `The access token for npm registry`

2021-03-24 07:43 UTC, pasqualedevita commented on azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_npm.go
> +		Description:      "Authentication token generated through npm (go to Npm > Account > Access Tokens -> Generate New Token)",
I renamed `serviceendpoint_npm.markdown` and changed `access_token` description as suggested.
thank you @xuzhang3

2021-03-24 07:44 UTC, pasqualedevita commented
> Hi @pasqualedevita Thanks for you PR. Few changes requested.
> `serviceendpoint_npm.markdown` should rename to `serviceendpoint_npm.html.markdown` otherwise the document navigation menu can not locate the document.

I renamed serviceendpoint_npm.markdown and changed access_token description as suggested.
thank you @xuzhang3

2021-03-25 08:15 UTC, xuzhang3 approved these changes
LGTM

2021-03-25 08:15 UTC, merged