adding 'DefaultBranch' into match_type setting
microsoft/terraform-provider-azuredevops pull request #591
Opened 2022-05-12 19:13 UTC by wetwicky

## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

The API accept passing a match_type that is 'DefaultBranch' to match the default defined for a repo, this PR is simply to add the missing value to the list of possible value we can passed to the Azure Devops API.

Issue Number: [issues 305](https://github.com/microsoft/terraform-provider-azuredevops/issues/305)

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

 Error: expected settings.0.scope.0.match_type to be one of [Exact Prefix], got DefaultBranch

## Other information

2022-05-12 19:40 UTC, wetwicky commented
I created this PR because PR #306 is missing the update of the markdown for branch_policy_status_check.html.markdown and because his check failed.

2022-05-18 13:47 UTC, wetwicky commented
hi @xuzhang3, is there anything missing to merge this PR?

2022-05-19 09:29 UTC, xuzhang3 commented
@wetwicky Can you add test to cover the changes?  I got some errors when create new policies based on this branch.
```log
Error: Error creating policy in Azure DevOps: TF402457: The settings for this policy are not correctly formatted. Error: RefName has to be empty if a matchKind of DefaultBranch is provided Path: 'scope[0]', line: 15, position: 5.

```

2022-05-20 18:40 UTC, wetwicky commented
> @wetwicky Can you add test to cover the changes? I got some errors when create new policies based on this branch.
> 
> ```
> Error: Error creating policy in Azure DevOps: TF402457: The settings for this policy are not correctly formatted. Error: RefName has to be empty if a matchKind of DefaultBranch is provided Path: 'scope[0]', line: 15, position: 5.
> ```
> 
> Ref: https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/acceptancetests/resource_branchpolicy_test.go

to use `DefaultBranch`, repository_ref should be `null` (not set)

Was the error you got inside one of the acceptance test or was it a manual test?

2022-05-23 07:48 UTC, xuzhang3 commented
@wetwicky manual test,  `repoId` and `repoRef` are set to empty string by default, if `match_type` is `DefaultBranch`, both   `repoId` and `repoRef` should be explicitly set to `null`.

2022-05-27 14:12 UTC, wetwicky commented
@xuzhang3  i added the acceptance test as requested and the documentation mentions to not set the value for repoId and repoRef

2022-05-30 08:29 UTC, xuzhang3 requested changes
@wetwicky  A few change request. 
1. I got error when run `TestAccBranchPolicyStatusCheck_CreateAndUpdate`
  ```log
   === RUN   TestAccBranchPolicyStatusCheck_CreateAndUpdate
=== PAUSE TestAccBranchPolicyStatusCheck_CreateAndUpdate
=== CONT  TestAccBranchPolicyStatusCheck_CreateAndUpdate
    resource_branchpolicy_test.go:332: Step 1/4 error: Error running apply: exit status 1
        
        Error: Error creating policy in Azure DevOps: TF402457: The settings for this policy are not correctly formatted. Error: RefName has to be empty if a matchKind of DefaultBranch is provided Path: 'scope[0]', line: 15, position: 5.
        
   ```
2. if `matchKind=DefaultBranch`,  provider should check the `repositoryId` and `refName` and raise an error when  there are not `nil`. 
 Example of `common.go -> expandSettings`:
```go
func expandSettings(d *schema.ResourceData) map[string]interface{} {
	settingsList := d.Get(SchemaSettings).([]interface{})
	settings := settingsList[0].(map[string]interface{})
	settingsScopes := settings[SchemaScope].([]interface{})

	scopes := make([]map[string]interface{}, len(settingsScopes))
	for index, scope := range settingsScopes {
		scopeMap := scope.(map[string]interface{})

		scopeSetting := map[string]interface{}{}
		if repoID, ok := scopeMap[SchemaRepositoryID]; ok {
			if repoID == "" {
				scopeSetting["repositoryId"] = nil
			} else {
				scopeSetting["repositoryId"] = repoID
			}
		}
		if repoRef, ok := scopeMap[SchemaRepositoryRef]; ok {
			if repoRef == "" {
				scopeSetting["refName"] = nil
			} else {
				scopeSetting["refName"] = repoRef
			}
		}
		if matchType, ok := scopeMap[SchemaMatchType]; ok {
			scopeSetting["matchKind"] = matchType
		}
		if strings.EqualFold(scopeSetting["matchKind"].(string), matchTypeDefaultBranch) &&
			(scopeSetting["repositoryId"] != nil || scopeSetting["refName"] != nil) {
			//TODO return fmt.Errorf("conflict settings")
		}

		scopes[index] = scopeSetting
	}
	return map[string]interface{}{
		SchemaScope: scopes,
	}
}
```

2022-05-30 08:29 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +					resource.TestCheckResourceAttr(statusCheckTfNode, "settings.0.scope.repository_ref", ""),
```suggestion
					resource.TestCheckResourceAttr(statusCheckTfNode, "settings.0.scope.0.match_type", "DefaultBranch"),
					resource.TestCheckResourceAttr(statusCheckTfNode, "settings.0.scope.0.repository_ref", ""),
```

2022-05-30 08:29 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +	return getBranchPolicyHcl("azuredevops_branch_policy_status_check", enabled, blocking, settings, repositoryRef, matchType)
`getBranchPolicyHcl` will set  the `repository_id  = azuredevops_git_repository.repository.id`,  need to  generate new test script.

2022-05-31 08:20 UTC, xuzhang3 requested changes

2022-05-31 08:20 UTC, xuzhang3 commented on website/docs/r/branch_policy_build_validation.html.markdown
> +      repository_ref = null
`repository_id` and `repository_ref` should not set when  `match_type     = "DefaultBranch"`
```suggestion
      match_type     = "DefaultBranch"
```

2022-05-31 08:20 UTC, xuzhang3 commented on website/docs/r/branch_policy_comment_resolution.html.markdown
> +      repository_ref = null
same above

2022-05-31 08:20 UTC, xuzhang3 commented on website/docs/r/branch_policy_merge_types.html.markdown
> +      repository_ref = null
same above

2022-05-31 08:20 UTC, xuzhang3 commented on website/docs/r/branch_policy_min_reviewers.html.markdown
> +      match_type     = "DefaultBranch"
same above

2022-05-31 08:20 UTC, xuzhang3 commented on website/docs/r/branch_policy_status_check.html.markdown
> +      repository_ref = null
same above

2022-05-31 08:20 UTC, xuzhang3 commented on website/docs/r/branch_policy_work_item_linking.html.markdown
> +      repository_ref = null
same above

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/service/policy/branch/common.go
> +			return nil, fmt.Errorf("conflicting settings, 'repository_id' is set to %q and 'repository_ref' is set to %q but neither must be set when using a 'match_type' of %q, ",
`scopeSetting["refName"]` will be `nil` when `matchKind=DefaultBranch`,
```suggestion
			return nil, fmt.Errorf(" neither 'repository_id' nor 'repository_ref' can be set when 'match_type=DefaultBranch'")
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getMinReviewersHcl(true, true, 1, false, "null", "exact"),
`repoRef` should be set when matchType=Exact
```suggestion
				Config: getMinReviewersHcl(true, true, 1, false, "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getMinReviewersHcl(false, false, 2, true, "null", "exact"),
```suggestion
				Config: getMinReviewersHcl(false, false, 2, true, "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getAutoReviewersHcl(true, true, false, "auto reviewer", fmt.Sprintf("\"%s\",\"%s\"", "*/API*.cs", "README.md"), "null", "exact"),
```suggestion
				Config: getAutoReviewersHcl(true, true, false, "auto reviewer", fmt.Sprintf("\"%s\",\"%s\"", "*/API*.cs", "README.md"), "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getAutoReviewersHcl(false, false, true, "new auto reviewer", fmt.Sprintf("\"%s\",\"%s\"", "*/API*.cs", "README.md"), "null", "exact"),
```suggestion
				Config: getAutoReviewersHcl(false, false, true, "new auto reviewer", fmt.Sprintf("\"%s\",\"%s\"", "*/API*.cs", "README.md"), "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getBuildValidationHcl(true, true, "build validation", 0, "null", "exact"),
```suggestion
				Config: getBuildValidationHcl(true, true, "build validation", 0, "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getBuildValidationHcl(false, false, "build validation rename", 720, "null", "exact"),
```suggestion
Config: getBuildValidationHcl(false, false, "build validation rename", 720, "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getBranchPolicyHcl(resourceName, true, true, "", "azuredevops_git_repository.repository.id", "null", "exact"),
```suggestion
				Config: getBranchPolicyHcl(resourceName, true, true, "", "azuredevops_git_repository.repository.id", "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getBranchPolicyHcl(resourceName, false, false, "", "azuredevops_git_repository.repository.id", "null", "exact"),
```suggestion
				Config: getBranchPolicyHcl(resourceName, false, false, "", "azuredevops_git_repository.repository.id", "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getBranchPolicyHcl(resourceName, true, true, "", "azuredevops_git_repository.repository.id", "null", "exact"),
```suggestion
				Config: getBranchPolicyHcl(resourceName, true, true, "", "azuredevops_git_repository.repository.id", "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getBranchPolicyHcl(resourceName, false, false, "", "azuredevops_git_repository.repository.id", "null", "exact"),
```suggestion
				Config: getBranchPolicyHcl(resourceName, false, false, "", "azuredevops_git_repository.repository.id", "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getMergeTypesHcl(true, true, true, true, true, true, "null", "exact"),
```suggestion
Config: getMergeTypesHcl(true, true, true, true, true, true, "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getMergeTypesHcl(false, false, false, false, false, false, "null", "exact"),
```suggestion
				Config: getMergeTypesHcl(false, false, false, false, false, false, "\"refs/heads/release\"", "Exact"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				Config: getStatusCheckHcl(false, false, "abc-2", false, "conditional", "null", "\"ref/heads/release\"", "prefix"),
```suggestion
				Config: getStatusCheckHcl(false, false, "abc-2", false, "conditional", "null", "\"refs/heads/release\"", "Prefix"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +					resource.TestCheckResourceAttr(statusCheckTfNode, "settings.0.scope.0.match_type", "prefix"),
```suggestion
resource.TestCheckResourceAttr(statusCheckTfNode, "settings.0.scope.0.match_type", "Prefix"),
```

2022-05-31 08:20 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_branchpolicy_test.go
> +				),
```suggestion
				Config: getStatusCheckHcl(false, false, "abc-3", false, "conditional", "null", "\"refs/heads/release\"", "Exact"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(statusCheckTfNode, "settings.0.name", "abc-3"),
					resource.TestCheckResourceAttr(statusCheckTfNode, "settings.0.scope.0.match_type", "Exact"),
					resource.TestCheckResourceAttr(statusCheckTfNode, "settings.0.scope.0.repository_id", ""),
					resource.TestCheckResourceAttr(statusCheckTfNode, "settings.0.scope.0.repository_ref", "refs/heads/release"),
				),
```

2022-05-31 19:00 UTC, wetwicky commented
Hi @xuzhang3 , i merged your suggestions. let me know if we you want anything else

2022-05-31 19:26 UTC, wetwicky reviewed
accept sugestions

2022-06-01 09:19 UTC, xuzhang3 commented
```log
=== RUN   TestAccBranchPolicyStatusCheckBasic
--- PASS: TestAccBranchPolicyStatusCheckBasic (165.20s)
=== RUN   TestAccBranchPolicyStatusCheckComplete
--- PASS: TestAccBranchPolicyStatusCheckComplete (85.98s)
=== RUN   TestAccBranchPolicyStatusCheckUpdate
--- PASS: TestAccBranchPolicyStatusCheckUpdate (103.54s)
=== RUN   TestAccBranchPolicyMinReviewers_CreateAndUpdate
=== PAUSE TestAccBranchPolicyMinReviewers_CreateAndUpdate
=== RUN   TestAccBranchPolicyAutoReviewers_CreateAndUpdate
=== PAUSE TestAccBranchPolicyAutoReviewers_CreateAndUpdate
=== RUN   TestAccBranchPolicyBuildValidation_CreateAndUpdate
=== PAUSE TestAccBranchPolicyBuildValidation_CreateAndUpdate
=== RUN   TestAccBranchPolicyWorkItemLinking_CreateAndUpdate
=== PAUSE TestAccBranchPolicyWorkItemLinking_CreateAndUpdate
=== RUN   TestAccBranchPolicyCommentResolution_CreateAndUpdate
=== PAUSE TestAccBranchPolicyCommentResolution_CreateAndUpdate
=== RUN   TestAccBranchPolicyMergeTypes_CreateAndUpdate
=== PAUSE TestAccBranchPolicyMergeTypes_CreateAndUpdate
=== RUN   TestAccBranchPolicyStatusCheck_CreateAndUpdate
=== PAUSE TestAccBranchPolicyStatusCheck_CreateAndUpdate
=== CONT  TestAccBranchPolicyMinReviewers_CreateAndUpdate
=== CONT  TestAccBranchPolicyCommentResolution_CreateAndUpdate
=== CONT  TestAccBranchPolicyStatusCheck_CreateAndUpdate
=== CONT  TestAccBranchPolicyMergeTypes_CreateAndUpdate
=== CONT  TestAccBranchPolicyBuildValidation_CreateAndUpdate
=== CONT  TestAccBranchPolicyWorkItemLinking_CreateAndUpdate
=== CONT  TestAccBranchPolicyAutoReviewers_CreateAndUpdate
--- PASS: TestAccBranchPolicyWorkItemLinking_CreateAndUpdate (161.52s)
--- PASS: TestAccBranchPolicyCommentResolution_CreateAndUpdate (165.88s)
--- PASS: TestAccBranchPolicyBuildValidation_CreateAndUpdate (176.58s)
--- PASS: TestAccBranchPolicyAutoReviewers_CreateAndUpdate (390.92s)
--- PASS: TestAccBranchPolicyStatusCheck_CreateAndUpdate (404.83s)
--- PASS: TestAccBranchPolicyMinReviewers_CreateAndUpdate (425.71s)
--- PASS: TestAccBranchPolicyMergeTypes_CreateAndUpdate (449.49s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        807.463s

```

2022-06-01 09:41 UTC, xuzhang3 commented
@wetwicky   LGTM

2022-06-01 09:41 UTC, xuzhang3 approved these changes

2022-06-01 09:42 UTC, merged