add resources build_folder & build_folder_permissions
microsoft/terraform-provider-azuredevops pull request #604
Opened 2022-06-10 14:36 UTC by bobmhong

## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission. (note: when running make ci locally, I noticed linting errors in the website docs, but not on any files I added)
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Implement resources azuredevops_build_folder and azuredevops_build_folder_permissions. 

Issue Number:
https://github.com/microsoft/terraform-provider-azuredevops/issues/353

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information

2022-06-10 14:36 UTC, ghost commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/microsoft/terraform-provider-azuredevops?pullRequest=604) <br/>All CLA requirements met.

2022-06-28 06:21 UTC, xuzhang3 requested changes

2022-06-28 06:21 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_folder_test.go
> +func TestBuildFolder(t *testing.T) {
Acctest function should named with `TestAcc` prefix

2022-06-28 06:21 UTC, xuzhang3 commented on azuredevops/internal/service/build/resource_build_folder.go
> +	"strings"
```suggestion
	"fmt"
	"log"
	"strings"
```

2022-06-28 06:21 UTC, xuzhang3 commented on azuredevops/internal/service/build/resource_build_folder.go
> +// ResourceBuildDefinition schema and implementation for build folder resource
```suggestion
// ResourceBuildFolder schema and implementation for build folder resource
```

2022-06-28 06:21 UTC, xuzhang3 commented on azuredevops/internal/service/build/resource_build_folder.go
> +		return fmt.Errorf("error creating resource Build Folder: %+v", err)
```suggestion
				return fmt.Errorf(" failed creating resource Build Folder, project ID: %s. Error: %+v", projectID, err)

```

2022-06-28 06:21 UTC, xuzhang3 commented on azuredevops/internal/service/build/resource_build_folder.go
> +		return err
```suggestion
		return fmt.Errorf(" failed to expand build folder configurations. Project ID: %s , Error: %+v", projectID, err)
```

2022-06-28 06:21 UTC, xuzhang3 commented on azuredevops/internal/service/build/resource_build_folder.go
> +		return err
```suggestion
		return fmt.Errorf("failed to update build folder.  Project ID: %s, Error: %+v ", projectID, err)
```

2022-06-28 06:21 UTC, xuzhang3 commented on azuredevops/internal/service/build/resource_build_folder.go
> +	})
```suggestion
	createdBuild, err := clients.BuildClient.CreateFolder(clients.Ctx, build.CreateFolderArgs{
		Folder: &build.Folder{
			Description: &description,
			Path:        &path,
			Project: &core.TeamProjectReference{
				Id: &projectUuid,
			},
		},
		Project: &project,
		Path:    &path,
	})
```

2022-06-28 06:21 UTC, xuzhang3 commented on azuredevops/internal/service/permissions/resource_build_folder_permissions.go
> +		return "", err
```suggestion
		return "", fmt.Errorf(" faild to get the folder. Project ID: %s, path: %s. %+v", projectID, buildFolderPath, err)
```

2022-06-28 06:21 UTC, xuzhang3 commented on main.go
> +		Debug: debug,
```suggestion
		Debug:        debug,
		ProviderAddr: "registry.terraform.io/microsoft/azuredevops",
```

2022-06-28 06:21 UTC, xuzhang3 commented on website/docs/r/build_folder_permissions.html.markdown
> +resource "azuredevops_build_folder_permissions" "example" {
The example `azuredevops_build_folder_permissions.example`  missing the path configuration `path        = azuredevops_build_folder.example.path`

2022-08-02 15:17 UTC, bobmhong commented
@xuzhang3 Thanks for the review - I've added a commit with your suggested changes.

2022-08-03 06:39 UTC, xuzhang3 requested changes
@bobmhong   a few changes requested, others LGTM.
1. `resource_folder_test.go` should rename to `resource_build_folder_test`
2. `website/docs/r/build_folder.html.markdown` and `website/docs/r/build_folder_permissions.html.markdown` should add to `azuredevops.erb`

2022-08-05 03:30 UTC, xuzhang3 commented
@bobmhong LGTM  🚢

2022-08-05 03:30 UTC, xuzhang3 approved these changes

2022-08-05 03:30 UTC, merged