Add Workitem Resource
microsoft/terraform-provider-azuredevops pull request #659
Opened 2022-10-28 09:08 UTC by IronMania

## All Submissions:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.
* [ ] My code follows the code style of this project.
* [ ] I ran lint checks locally prior to submission.
* [ ] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Issue Number:

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [ ] No

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information

2022-10-28 09:19 UTC, IronMania commented
@microsoft-github-policy-service agree [company="Pexon Consulting GmbH"]

2022-10-28 09:19 UTC, IronMania commented
@microsoft-github-policy-service agree company="Pexon Consulting GmbH"

2022-10-30 14:45 UTC, IronMania commented
made a comment on the ticket, about the state of the created ticket

2022-10-31 08:42 UTC, xuzhang3 commented
@IronMania can you add the AccTest for the new resource?
Ref: https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/acceptancetests/resource_serviceendpoint_bitbucket_test.go

2022-11-01 09:54 UTC, IronMania commented
@xuzhang3 I added the AccTest. Can you please review the idea of having a desired state, which I wrote in my ticket? Because that would be a breaking change if we implement it later.

2022-11-01 14:33 UTC, IronMania commented
i also added tags

2023-02-17 08:25 UTC, xuzhang3 requested changes

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +				Optional:     false,
`Optional: false,` can be removed as `Required: true,`, only one of this is required.

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +				Required:     true,
save as above, only one of `Optional` or `Required` is requried

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +				DiffSuppressFunc: suppress.CaseDifference,
project ID is UUID, `DiffSuppressFunc`  can be remove.

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +	}
```suggestion
	
	operations := GetPatchOperations(d)

	args := workitemtracking.CreateWorkItemArgs{
		Project:  converter.String(d.Get("project_id").(string)),
		Type:     converter.String(d.Get("type").(string)),
		Document: &operations,
	}
```

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +	id, _ := strconv.Atoi(d.Id())
parse error should not be ignored.

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +func GetPatchOperations(d *schema.ResourceData) []webapi.JsonPatchOperation {
```suggestion
func expandPatchOperations(d *schema.ResourceData) []webapi.JsonPatchOperation {
```

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +func SetCustomFields(d *schema.ResourceData, operations []webapi.JsonPatchOperation) []webapi.JsonPatchOperation {
```suggestion
func expandCustomFields(d *schema.ResourceData, operations []webapi.JsonPatchOperation) []webapi.JsonPatchOperation {
```

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +func SetSystemFields(d *schema.ResourceData, operations []webapi.JsonPatchOperation) []webapi.JsonPatchOperation {
```suggestion
func expandSystemFields(d *schema.ResourceData, operations []webapi.JsonPatchOperation) []webapi.JsonPatchOperation {
```

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +func SetTags(d *schema.ResourceData, operations []webapi.JsonPatchOperation) []webapi.JsonPatchOperation {
```suggestion
func expandTags(d *schema.ResourceData, operations []webapi.JsonPatchOperation) []webapi.JsonPatchOperation {
```

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +func GetFields(d *schema.ResourceData, m *map[string]interface{}) {
```suggestion
func flattenFields(d *schema.ResourceData, input *map[string]interface{}) {
```

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +	systemFieldReverseMapping := datahelper.ReverseMap(systemFieldMapping)
recommend define a local reverse map instead of get from the origin map in case for concurrent failure in some scenario.

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +	for terraformProperty, apiName := range *&systemFieldReverseMapping {
```suggestion
	for terraformProperty, apiName := range systemFieldReverseMapping {
```

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +	custom_fields := make(map[string]interface{})
Local variables follow the camel pattern.
`custom_fields` -> `customFields`

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +		if ok {
```suggestion
		if v, ok := systemFieldMapping[key]; ok {
```

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +			key_without_custom := strings.ReplaceAll(key, "Custom.", "")
Local variables follow the camel pattern.

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +			custom_fields[key_without_custom] = value
Local variables follow the camel pattern.

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/utils/datahelper/data_helper.go
> +	n := make(map[string]string, len(m))
need null/empty checks for input parameters

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/service/workitemtracking/resource_workitem.go
> +	}
```suggestion
	if err != nil {
		if utils.ResponseWasNotFound(err) {
			d.SetId("")
			return nil
		}
		return err
	}
```

2023-02-17 08:25 UTC, xuzhang3 commented on website/docs/r/workitem.html.markdown
> +}
```suggestion
resource "azuredevops_project" "example" {
  name               = "Example Project"
  work_item_template = "Agile"
  version_control    = "Git"
  visibility         = "private"
  description        = "Managed by Terraform"
}

resource "azuredevops_workitem" "example" {
  project_id    = data.azuredevops_project.example.id
  title         = "Testing Terraform Item"
  type          = "Issue"
  state = "Active"
  tags  = ["Tag"]
}
```

2023-02-17 08:25 UTC, xuzhang3 commented on website/docs/r/workitem.html.markdown
> +```
```suggestion

Work Items  can be imported using the project name/variable group ID or by the project Guid/variable group ID, e.g.

```sh
terraform import azuredevops_workitem.example "Example Project/10"
```

or

```sh
terraform import azuredevops_workitem.example 00000000-0000-0000-0000-000000000000/0
```
```

2023-02-17 08:25 UTC, xuzhang3 commented on website/docs/r/workitem.html.markdown
> +* `project_id` - (Required) UUID of the Project.
The ID of the oprp
```suggestion
* `project_id` - (Required)  The ID of the project.
```

2023-02-17 08:25 UTC, xuzhang3 commented on azuredevops/internal/acceptancetests/resource_workitem_test.go
> +func TestAccWorkitem_CreateAndUpdate(t *testing.T) {
1.  Please split the `createAndUpdate` into `create` and `update`? 
2. Add an import test case to cover the import fucntion.
Example: https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/acceptancetests/resource_serviceendpoint_aws_test.go#L112

2023-02-28 08:18 UTC, IronMania commented on azuredevops/internal/acceptancetests/resource_workitem_test.go
> +func TestAccWorkitem_CreateAndUpdate(t *testing.T) {
I hope i did what you meant. I am not quite confident in my go/terraform testing skills.

2023-02-28 08:35 UTC, IronMania commented
@xuzhang3 i implemented the changes but I lack the skill "reading the errors in the build" :-(
I could run the acceptance test locally

2023-03-01 07:40 UTC, IronMania commented on azuredevops/internal/utils/datahelper/data_helper.go
> +	n := make(map[string]string, len(m))
i removed that function

2023-03-03 08:17 UTC, xuzhang3 commented
@IronMania  how do you running the  acctest? If you run with `make acctest ...`, you can add 
```shell
export TF_LOG=TRACE
export TF_LOG_PATH=<log_path>
```
to output the log to the specific file or direct to console without the log file path.

2023-03-03 13:35 UTC, IronMania commented
@xuzhang3 sorry if I was unclear: The build from the pipeline did not run. 
Locally I use this to run the tests and it works for all acctests that I wrote:
`TF_ACC=1 /usr/local/go/bin/go test -timeout 30m -run ^TestAccWorkitem_Import$ github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests -v -tags=all -args -test.v`

2023-03-06 06:05 UTC, xuzhang3 commented
@IronMania you need set the env variable first then run `go test ...`
```shell
export TF_LOG=TRACE
export TF_LOG_PATH=<log path>
```

Run test:
![image](https://user-images.githubusercontent.com/57888764/223031185-15ad3654-80c3-4035-bc5f-ffbf1ebe815e.png)

Logs:
![image](https://user-images.githubusercontent.com/57888764/223031277-6eea23dc-20e2-4c54-b07d-05a584dbb97d.png)

2023-03-06 07:14 UTC, IronMania commented
@xuzhang3 I am still confused why you want my local testlog. They run on my machine and pass! So why should I set the log level on my local machine, if they run?


``` bash
root@9ac8db44677a:/workspaces/terraform-provider-azuredevops# TF_ACC=1 /usr/local/go/bin/go test -timeout 30m -run ^TestAccWorkitem_Import$ github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests -v -tags=all -args -test.v^[[B^[[A=== RUN   TestAccWorkitem_Import
=== PAUSE TestAccWorkitem_Import
=== CONT  TestAccWorkitem_Import
--- PASS: TestAccWorkitem_Import (47.30s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests 47.332s
```


``` bash
tail testLog 
2023-03-06T07:01:10.408Z [TRACE] sdk.proto: Served request: tf_rpc=ApplyResourceChange tf_resource_type=azuredevops_project tf_req_id=f7f88765-c883-8774-cb35-ffbf0b92e813 tf_provider_addr=registry.terraform.io/hashicorp/azuredevops tf_proto_version=5.3
2023-03-06T07:01:10.450Z [TRACE] sdk.helper_resource: Called Terraform CLI destroy command: test_working_directory=/tmp/plugintest1572089303/work2827802978 test_name=TestAccWorkitem_Import test_step_number=2 test_terraform_path=/usr/local/bin/terraform
2023-03-06T07:01:10.453Z [TRACE] sdk.helper_resource: Called wrapped Terraform CLI command: test_working_directory=/tmp/plugintest1572089303/work2827802978 test_name=TestAccWorkitem_Import test_step_number=2 test_terraform_path=/usr/local/bin/terraform
2023-03-06T07:01:10.454Z [DEBUG] sdk.helper_resource: Stopping providers: test_name=TestAccWorkitem_Import test_step_number=2 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest1572089303/work2827802978
2023-03-06T07:01:10.456Z [TRACE] sdk.helper_resource: Waiting for providers to stop: test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest1572089303/work2827802978 test_name=TestAccWorkitem_Import test_step_number=2
2023-03-06T07:01:10.457Z [TRACE] sdk.helper_resource: Providers have successfully stopped: test_name=TestAccWorkitem_Import test_step_number=2 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest1572089303/work2827802978
2023-03-06T07:01:10.458Z [TRACE] sdk.helper_resource: Using TestCase CheckDestroy: test_name=TestAccWorkitem_Import test_step_number=2 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest1572089303/work2827802978
2023-03-06T07:01:10.460Z [DEBUG] sdk.helper_resource: Calling TestCase CheckDestroy: test_name=TestAccWorkitem_Import test_step_number=2 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest1572089303/work2827802978
2023-03-06T07:01:10.560Z [DEBUG] sdk.helper_resource: Called TestCase CheckDestroy: test_name=TestAccWorkitem_Import test_step_number=2 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest1572089303/work2827802978
2023-03-06T07:01:10.567Z [DEBUG] sdk.helper_resource: Finished TestCase: test_step_number=2 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest1572089303/work2827802978 test_name=TestAccWorkitem_Import
root@9ac8db44677a:/workspaces/terraform-provider-azuredevops# 
```

2023-03-06 07:27 UTC, xuzhang3 commented
> @xuzhang3 i implemented the changes but I lack the skill "reading the errors in the build" :-( I could run the acceptance test locally

@IronMania  you mentionedcannot `reading the erroring in the build`. So I ask if you can provider the test logs, then I can help locate the issue.

2023-03-06 07:37 UTC, xuzhang3 commented
@IronMania I see what you mean, my fault. You can ignore pipeline build error. That is an unit test error.

2023-03-06 08:12 UTC, xuzhang3 approved these changes

2023-03-06 08:13 UTC, xuzhang3 commented
LGTM 🚢

2023-03-06 08:13 UTC, merged