Make `agent_pool_id` optional in resource `azuredevops_agent_queue`
microsoft/terraform-provider-azuredevops pull request #906
Opened 2023-10-20 00:21 UTC by BHoggs

## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

The API does not require a Pool ID to be specified when creating an Agent Queue, alternatively only a name needs to be specified.
In this scenario, the pool gets automatically created without explicitly requesting it. This is useful for creating agent pools at the project-level without needing org-level permissions to create pools.

Issue Number: #456 

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This is my first attempt at a PR for a terraform module and I'm pretty new at Go, so please let me know if I should have done anything differently!

2023-10-20 02:08 UTC, BHoggs commented
@microsoft-github-policy-service agree company="Computer Concepts Limited"

2023-10-29 20:02 UTC, BHoggs commented
@xuzhang3 Anything missing or need to be changed for this to get merged? Keen to get this across the line to unblock something on our end. :)

2023-11-17 09:09 UTC, xuzhang3 requested changes

2023-11-17 09:09 UTC, xuzhang3 commented on azuredevops/internal/service/taskagent/resource_agent_queue.go
>  	}
```suggestion
	if v, exist := d.GetOk(agentPoolID); exist {
		queue.Pool = &taskagent.TaskAgentPoolReference{
			Id: converter.Int(v.(int)),
		}
	}
```

2023-11-17 09:09 UTC, xuzhang3 commented on website/docs/r/agent_queue.html.markdown
> +> When `agent_pool_id` is specified, the agent queue name will be derived from the agent pool name.
```suggestion
~> **NOTE:**
    One of `name` or `agent_pool_id` must be specified, but not both.
    When `agent_pool_id` is specified, the agent queue name will be derived from the agent pool name.
```

2023-11-21 02:50 UTC, xuzhang3 commented
```log
=== RUN   TestAccResourceAgentQueue_CreateAndUpdate
=== PAUSE TestAccResourceAgentQueue_CreateAndUpdate
=== CONT  TestAccResourceAgentQueue_CreateAndUpdate
--- PASS: TestAccResourceAgentQueue_CreateAndUpdate (55.28s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        55.665s

```

2023-11-21 02:50 UTC, xuzhang3 approved these changes

2023-11-21 02:50 UTC, xuzhang3 commented
@BHoggs LGTM

2023-11-21 02:50 UTC, merged